"""
app.py — Provenance Guard
AI content attribution API for creative sharing platforms.

Endpoints:
    POST /submit   — classify text content
    POST /appeal   — contest a classification
    GET  /log      — view audit log entries
"""

import json
import math
import os
import re
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

# ── Rate limiting ─────────────────────────────────────────────────────────────
# 10 per minute: a real writer submits infrequently; this blocks rapid scripts
# 100 per day: generous daily cap for legitimate heavy users
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Groq client ───────────────────────────────────────────────────────────────
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ── Audit log (in-memory + persisted to audit_log.json) ──────────────────────
LOG_FILE = "audit_log.json"


def load_log() -> list:
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


def save_log(entries: list):
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)


def append_log(entry: dict):
    entries = load_log()
    entries.append(entry)
    save_log(entries)


def update_log_entry(content_id: str, updates: dict) -> bool:
    """Update an existing log entry by content_id. Returns True if found."""
    entries = load_log()
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            save_log(entries)
            return True
    return False


# ── Signal 1: LLM-based classification ───────────────────────────────────────

def classify_with_llm(text: str) -> float:
    """
    Ask Groq to assess whether the text is AI-generated.
    Returns a float 0.0–1.0 where higher = more likely AI-generated.
    """
    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and assess the probability that it was generated by an AI system (not written by a human).

Consider:
- Uniformity of sentence structure and length
- Presence or absence of genuine personal voice
- Formulaic transitions and hedging language ("it is important to note", "furthermore", "in conclusion")
- Unexpected word choices, self-correction, or genuine uncertainty typical of human writing
- Overly balanced, sanitized, or diplomatic tone

Respond with ONLY a JSON object in this exact format:
{{"ai_probability": 0.85, "reasoning": "brief explanation"}}

The ai_probability must be a float between 0.0 and 1.0.
0.0 = definitely human-written
1.0 = definitely AI-generated

Text to analyze:
{text}"""

    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()

        # Extract JSON from response
        match = re.search(r'\{.*?\}', raw, re.DOTALL)
        if match:
            data = json.loads(match.group())
            score = float(data.get("ai_probability", 0.5))
            return max(0.0, min(1.0, score))
        return 0.5  # fallback if parsing fails

    except Exception as e:
        print(f"LLM signal error: {e}")
        return 0.5  # neutral fallback on error


# ── Signal 2: Stylometric heuristics ─────────────────────────────────────────

def compute_stylometric_score(text: str) -> float:
    """
    Compute statistical properties of text that differ between human and AI writing.
    Returns a float 0.0–1.0 where higher = more AI-like.

    Metrics:
    - Sentence length variance (low variance → more AI-like)
    - Type-token ratio (low diversity → more AI-like)
    - Punctuation density (low idiosyncratic punctuation → more AI-like)
    """
    if not text or len(text.strip()) < 20:
        return 0.5  # too short to score reliably

    # Split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5  # not enough sentences

    # ── Metric 1: Sentence length variance ───────────────────────────────────
    # AI text tends to have uniform sentence lengths
    sentence_lengths = [len(s.split()) for s in sentences]
    mean_len = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    std_dev = math.sqrt(variance)

    # Normalize: std_dev of 0 (perfectly uniform) → 1.0 (AI-like)
    # std_dev of 10+ (very variable) → 0.0 (human-like)
    length_variance_score = max(0.0, 1.0 - (std_dev / 10.0))

    # ── Metric 2: Type-token ratio (vocabulary diversity) ────────────────────
    # AI text tends to repeat vocabulary; human writing is more diverse
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) == 0:
        ttr_score = 0.5
    else:
        unique_words = len(set(words))
        ttr = unique_words / len(words)
        # Low TTR (< 0.4) → AI-like (score near 1.0)
        # High TTR (> 0.7) → human-like (score near 0.0)
        ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.3) / 0.5)))

    # ── Metric 3: Punctuation idiosyncrasy ───────────────────────────────────
    # Humans use dashes, ellipses, exclamation marks more freely
    idiosyncratic = len(re.findall(r'[—–\-]{2,}|\.{2,}|!{1,}|\?{1,}', text))
    total_chars = len(text)
    idio_density = idiosyncratic / max(total_chars, 1)

    # Low idiosyncrasy → more AI-like
    # Normalize: 0 idio → 1.0, 0.02+ idio → 0.0
    punctuation_score = max(0.0, 1.0 - (idio_density / 0.02))

    # ── Combine metrics ───────────────────────────────────────────────────────
    stylometric_score = (
        length_variance_score * 0.40 +
        ttr_score * 0.35 +
        punctuation_score * 0.25
    )

    return round(max(0.0, min(1.0, stylometric_score)), 4)


# ── Confidence scoring ────────────────────────────────────────────────────────

def compute_confidence(llm_score: float, stylometric_score: float) -> float:
    """
    Combine both signal scores into a single confidence score.
    LLM signal: 60% weight (captures semantic holism)
    Stylometric: 40% weight (captures structural patterns)
    Higher score = more likely AI-generated.
    """
    confidence = (llm_score * 0.6) + (stylometric_score * 0.4)
    return round(max(0.0, min(1.0, confidence)), 4)


# ── Transparency label ────────────────────────────────────────────────────────

def generate_label(confidence: float) -> dict:
    """
    Map a confidence score to a transparency label.

    Thresholds (asymmetric — requires high confidence to label as AI):
    >= 0.80  → high-confidence AI
    0.40–0.79 → uncertain
    < 0.40   → high-confidence human
    """
    if confidence >= 0.72:
        pct = round(confidence * 100)
        return {
            "variant": "high_confidence_ai",
            "text": (
                f"⚠️ This content was likely generated by AI. "
                f"Our system is {pct}% confident in this assessment. "
                f"You may appeal if you believe this is incorrect."
            ),
        }
    elif confidence >= 0.40:
        pct = round(confidence * 100)
        return {
            "variant": "uncertain",
            "text": (
                f"❓ We could not confidently determine the origin of this content "
                f"({pct}% confidence). A human reviewer will assess this content."
            ),
        }
    else:
        pct = round((1 - confidence) * 100)
        return {
            "variant": "high_confidence_human",
            "text": (
                f"✅ This content appears to be human-written. "
                f"Our system is {pct}% confident in this assessment."
            ),
        }


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    Accept a piece of text for attribution analysis.

    Request body:
        {
            "text": "...",
            "creator_id": "..."
        }

    Response:
        {
            "content_id": "...",
            "attribution": "likely_ai" | "uncertain" | "likely_human",
            "confidence": 0.0–1.0,
            "llm_score": 0.0–1.0,
            "stylometric_score": 0.0–1.0,
            "label": { "variant": "...", "text": "..." },
            "status": "classified"
        }
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400
    if len(text) < 20:
        return jsonify({"error": "Text too short for analysis (minimum 20 characters)"}), 400

    # Generate unique content ID
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Run both detection signals
    llm_score = classify_with_llm(text)
    stylometric_score = compute_stylometric_score(text)

    # Combine into confidence score
    confidence = compute_confidence(llm_score, stylometric_score)

    # Map to attribution label
    if confidence >= 0.72:
        attribution = "likely_ai"
    elif confidence >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    label = generate_label(confidence)

    # Write to audit log
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label_variant": label["variant"],
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label,
        "status": "classified",
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    Contest a classification.

    Request body:
        {
            "content_id": "...",
            "creator_reasoning": "..."
        }

    Response:
        {
            "message": "...",
            "content_id": "...",
            "status": "under_review"
        }
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = data.get("content_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    appeal_timestamp = datetime.now(timezone.utc).isoformat()

    updated = update_log_entry(content_id, {
        "status": "under_review",
        "appeal_reasoning": reasoning,
        "appeal_timestamp": appeal_timestamp,
    })

    if not updated:
        return jsonify({"error": f"No submission found with content_id: {content_id}"}), 404

    return jsonify({
        "message": "Your appeal has been received and the content is now under review.",
        "content_id": content_id,
        "status": "under_review",
    })


@app.route("/log", methods=["GET"])
def get_log():
    """
    Return the most recent audit log entries.
    Query param: ?limit=N (default 20)
    """
    try:
        limit = int(request.args.get("limit", 20))
    except ValueError:
        limit = 20

    entries = load_log()
    recent = entries[-limit:][::-1]  # most recent first

    return jsonify({
        "total_entries": len(entries),
        "returned": len(recent),
        "entries": recent,
    })


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True, port=5000)
